### ISSUE TITLE
Handle multi-lines via list

### ISSUE THREAD

**Issue by timflutre** [sacabuche/RISparser#1]
Thanks a lot for implementing multi-line support! But could it be possible to keep multi-lines as a list instead of concatenating them into a single string? I am especially interested in this for the "N1" field which contains notes, often on multiple lines. So I would add "N1" to LIST_TYPES_TAG.

**Comment by sacabuche** [comment]
@timflutre how are N1 formated?

like this?

```
TY  - JOUR
N1 - first note
     now in the second line
```

or with a tag?

```
TY  - JOUR
N1 - first note
N1 - now in the second line
```

**Comment by timflutre** [comment]
Like the first case:

```
TY  - JOUR
N1 - first note
     now in the second line
```

At least, that's how they appear in [citeulike](http://www.citeulike.org/).

**Comment by sacabuche** [comment]
I can't find any example with N1, are this  really different notes?  ¿or is just one note in multiple lines?

Hey what about join it with \n? I feel that it must be a string, it will be the least surprising result, what do you think?

**Comment by timflutre** [comment]
Here is an [example](http://www.citeulike.org/user/timflutre/article/12171749). When you export it into RIS, the note appears on several lines, only the first starts with "N1". But indeed, you can keep the "\n" instead of using a list.

**Comment by sacabuche** [comment]
At the end I just changed N1 to list type

**Comment by timflutre** [comment]
Ok, sounds good, thanks! By the way, you should add your name as an author, and add a COPYING file with the [GPL-3](https://www.gnu.org/licenses/gpl.txt) to the repo. (This license is mentioned at the top of `RISparser/__init__.py`.)

**Comment by sacabuche** [comment]
thanks, I will, this afternoon :+1:
